version: 2
updates:
  - directory: "/"
    package-ecosystem: npm
    assignees:
      - glektarssza
    labels:
      - Dependency
    versioning-strategy: increase
    schedule:
      interval: weekly
      day: wednesday
      time: "12:00"
      timezone: Canada/Mountain
