# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      build-config:
        description: >
          The configuration to build the project under. Valid options are:
          * `development` - Create a development build.
          * `production` - Create a production build.
        type: string
        required: true
    secrets:
      github-token:
        description: >
          The GitHub access token to use for authenticated GitHub operations.
        required: false
    outputs:
      artifact-id:
        description: >
          The ID of the artifact uploaded as a result of this workflow.
        value: ${{jobs.build.outputs.artifact-id}}
      artifact-name:
        description: >
          The name of the artifact uploaded as a result of this workflow.
        value: ${{jobs.build.outputs.artifact-name}}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    outputs:
      artifact-id: ${{steps.upload-artifacts.outputs.artifact-id}}
      artifact-name: dist-${{matrix.build-config == 'development' && 'dev' || 'prod'}}
    strategy:
      fail-fast: true
      matrix:
        build-config:
          - development
          - production
        exclude:
          - build-config: ${{(inputs.build-config == 'development' && 'production') || (inputs.build-config == 'production' && 'development') || ''}}
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: glektarssza/webcraft
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
          lfs: true
      - id: setup-pnpm
        name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - id: setup-nodejs
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - id: install-dependencies
        name: Install dependencies
        run: pnpm -r install
      - id: build
        name: Build
        run: pnpm -r --filter '@glektarssza/webcraft...' run build:${{matrix.build-config == 'development' && 'dev' || 'prod'}}
      - id: upload-artifacts
        name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{matrix.build-config == 'development' && 'dev' || 'prod'}}
          path: ./dist/${{matrix.build-config == 'development' && 'dev' || 'prod'}}
