# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint
on:
  push:
  pull_request:
    branches:
      - main
  workflow_call:
    secrets:
      github-token:
        description: >
          The token to use for making authenticated requests to the GitHub APIs.
        required: true
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
          lfs: true
      - id: setup-pnpm
        name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - id: setup-nodejs
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - id: get-pnpm-store-directory
        name: Get pnpm store directory
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
      - id: setup-pnpm-cache
        name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{steps.get-pnpm-store-directory.outputs.PNPM_STORE_PATH}}
          key: ${{runner.os}}-pnpm-store-${{hashFiles('pnpm-lock.yaml')}}
          restore-keys: |
            ${{runner.os}}-pnpm-store-
      - id: install-dependencies
        name: Install dependencies
        run: pnpm -r install
      - id: prebuild-types
        name: Prebuild types
        run: pnpm -r --filter 'webcraft^...' run build:types
      - id: lint
        name: Lint
        run: pnpm -r run lint
