name: On Release
on:
  release:
    types:
      - published
jobs:
  build:
    name: Build
    permissions:
      contents: read
    uses: ./.github/workflows/build.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
    with:
      build-config: production
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    needs:
      - build
    environment:
      name: github-pages
      url: ${{steps.deploy-pages.outputs.page_url}}
    steps:
      - id: download-artifacts
        name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{needs.build.outputs.artifact-name}}
          path: dist
      - id: upload-pages-artifacts
        name: Upload Pages artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - id: deploy-pages
        name: Deploy Pages
        uses: actions/deploy-pages@v4
