name: Push
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
      - id: setup-nodejs
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - id: setup-pnpm
        name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
          run_install: false
      - id: get-pnpm-store-directory
        name: Get pnpm store directory
        run: echo "pnpm-store-path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - id: setup-pnpm-cache
        name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{steps.get-pnpm-store-directory.outputs.pnpm-store-path}}
          key: ${{runner.os}}-pnpm-store-${{hashFiles('**/pnpm-lock.yaml')}}
          restore-keys: |
            ${{runner.os}}-pnpm-store-
      - id: install-dependencies
        name: Install dependencies
        run: pnpm -r install
      - id: build-typescript-types
        name: Build Typescript Types
        run: pnpm -r run build:types
      - id: run-linter
        name: Run linter
        run: pnpm -r run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
      - id: setup-nodejs
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - id: setup-pnpm
        name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
          run_install: false
      - id: get-pnpm-store-directory
        name: Get pnpm store directory
        run: echo "pnpm-store-path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      - id: setup-pnpm-cache
        name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{steps.get-pnpm-store-directory.outputs.pnpm-store-path}}
          key: ${{runner.os}}-pnpm-store-${{hashFiles('**/pnpm-lock.yaml')}}
          restore-keys: |
            ${{runner.os}}-pnpm-store-
      - id: install-dependencies
        name: Install dependencies
        run: pnpm -r install
      - id: build-typescript-types
        name: Build Typescript Types
        run: pnpm -r run build:types
      - id: run-tests
        name: Run tests
        run: pnpm -r run test:ci
